### ISSUE TITLE
coldfront.project_projectattribute doesn't exist

### ISSUE THREAD

**Issue by wabrashear** [ubccr/hpc-toolset-tutorial#158]
I'm working my way through the tutorial but I am getting the following error when I try to create a new project:

```Environment:


Request Method: GET
Request URL: https://localhost:2443/project/1/

Django Version: 3.2.17
Python Version: 3.9.13
Installed Applications:
['django_su',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'crispy_forms',
 'sslserver',
 'django_q',
 'simple_history',
 'fontawesome_free',
 'coldfront.core.user',
 'coldfront.core.field_of_science',
 'coldfront.core.utils',
 'coldfront.core.portal',
 'coldfront.core.project',
 'coldfront.core.resource',
 'coldfront.core.allocation',
 'coldfront.core.grant',
 'coldfront.core.publication',
 'coldfront.core.research_output',
 'coldfront.plugins.slurm',
 'mozilla_django_oidc']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'simple_history.middleware.HistoryRequestMiddleware',
 'mozilla_django_oidc.middleware.SessionRefresh']



Traceback (most recent call last):
  File "/srv/www/venv/lib64/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/srv/www/venv/lib64/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/srv/www/venv/lib64/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/srv/www/venv/lib64/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/srv/www/venv/lib64/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)

The above exception ((1146, "Table 'coldfront.project_projectattribute' doesn't exist")) was the direct cause of the following exception:
  File "/srv/www/venv/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/www/venv/lib64/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/www/venv/lib64/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/www/venv/lib64/python3.9/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/srv/www/venv/lib64/python3.9/site-packages/django/contrib/auth/mixins.py", line 128, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/srv/www/venv/lib64/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/www/venv/lib64/python3.9/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/srv/www/venv/lib64/python3.9/site-packages/coldfront/core/project/views.py", line 124, in get_context_data
    attributes_with_usage = [attribute for attribute in project_obj.projectattribute_set.filter(
  File "/srv/www/venv/lib64/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/srv/www/venv/lib64/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/srv/www/venv/lib64/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/srv/www/venv/lib64/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/srv/www/venv/lib64/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/srv/www/venv/lib64/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/srv/www/venv/lib64/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/srv/www/venv/lib64/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/srv/www/venv/lib64/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/srv/www/venv/lib64/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/srv/www/venv/lib64/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/srv/www/venv/lib64/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/srv/www/venv/lib64/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/srv/www/venv/lib64/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)

Exception Type: ProgrammingError at /project/1/
Exception Value: (1146, "Table 'coldfront.project_projectattribute' doesn't exist")```

**Comment by dsajdak** [comment]
@wabrashear are you running an older version of the containers or have you pulled recent updates to the repo?  I did get this error a few weeks ago as well.  The project attributes are a new feature and the updates were conflicting with a pre-existing ColdFront database I already had in my environment.  I destroyed the containers and redownloaded everything, then it worked for me:
```
./hpcts destroy
./hpcts start
```

**Comment by wabrashear** [comment]
@dsajdak Thanks! I pulled the newest version of the containers. I tried destroying and re-starting but get the same error.

**Comment by dsajdak** [comment]
@wabrashear I'm not able to replicate this problem but we are in the middle of updating the containers for a conference in a few weeks.  I would recommend you wait until that update is done, blow it away and then try again.  I can let you know when the updates are ready on Dockerhub if you want.

**Comment by dsajdak** [comment]
@wabrashear Yes!  We'll be offering a full day tutorial at PEARC this year.

**Comment by wabrashear** [comment]
@dsajdak Awesome! I'll see you there!

**Comment by dsajdak** [comment]
@wabrashear the latest containers have been tested and published.  I recommend you do the following:

```
./hpcts destroy
git pull
./hpcts start
```

If this doesn't work, then try removing everything and starting fresh with:

```
./hpcts cleanup
./hpcts start
```
